---
driver:
  name: localhost

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: macosx-10
  - name: windows-2012R2
    attributes:
      java_se:
        force_i586: true

suites:
  - name: default
    run_list:
      - chrome
