language: ruby

sudo: required

matrix:
  include:
  - osx_image: xcode8
  - osx_image: xcode7.3
  - osx_image: xcode7.2
  - osx_image: xcode7.1
  - osx_image: xcode7
  - osx_image: xcode6.4
  - osx_image: beta-xcode6.3
  - osx_image: beta-xcode6.2
  - osx_image: beta-xcode6.1

before_install:
- rvm get head
- rvm install 2.2

script:
- KITCHEN_YAML=.kitchen.localhost.yml bundle exec kitchen verify macosx

branches:
  only:
  - macosx
